name: Deploy React Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run : docker build -t yashsojitra/gymbuddy-react .

      - name: Publish Image to Docker hub
        run: docker push yashsojitra/gymbuddy-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop previous running container if exists
        run: |
          if [ "$(docker ps -q -f name=react-app-container)" ]; then
            docker stop react-app-container
          fi
      
      - name: Remove previous container if exists
        run: |
          if [ "$(docker ps -a -q -f name=react-app-container)" ]; then
            docker rm react-app-container
          fi
              
      - name: Pull image from docker hub
        run: docker pull yashsojitra/gymbuddy-react:latest

      - name: run docker container
        run: docker run -d -p 3000:80 --name react-app-container yashsojitra/gymbuddy-react
